### ISSUE TITLE
Добавить clearByIblockTag()

### ISSUE THREAD

**Issue by TiGR** [webarchitect609/bitrix-cache#10]
Кэш поддерживает `addIblockTag()` но возможности так же почистить по ID инфоблока не даёт. Нужно либо руками собирать тэг для инфоблока, либо дёргать внутренности легаси битрикса, типа `CIBlockElement::clearIblockTagCache()`.

Было бы удобно иметь возможность почистить кэш по инфоблоку.

**Comment by webarchitect609** [comment]
Реализовано в [1.7.0](/webarchitect609/bitrix-cache/releases/tag/v1.7.0)
