### ISSUE TITLE
Возможность создавать тегированный кеш в замыкании

### ISSUE THREAD

**Issue by snezhig** [webarchitect609/bitrix-cache#15]
Сейчас, кеш по тегу возможен только в том случае, если какой-либо тег был задан до callback, что может быть неудобно, когда ключи для тега могут быть известны только в замыкании.

**Comment by webarchitect609** [comment]
```php
$cache = WebArch\BitrixCache\Cache::create();
$cache->callback(
    function () use ($cache) {
        $cache->addTag('closureTag');
    }
);
```

**Comment by snezhig** [comment]
Я так и пробовал, но не работает оно. Там же регистрация тегов идёт до вызова callback по коду, а в конце идёт end, который просто закрывает.

**Comment by snezhig** [comment]
![изображение](https://user-images.githubusercontent.com/3987716/103139314-d9301d00-46eb-11eb-8f08-882907949e88.png)
Вот тут регистрация тегов и судя по функции только, если теги уже были заранее заданы.
Либо я что-то не так делаю.

**Comment by webarchitect609** [comment]
И правда, спасибо. Подумаю над тем, как это можно решить.

**Comment by snezhig** [comment]
Мне для решения пришлось написать небольшого наследника на скорую руку, может какие идеи появятся. Спасибо.
```php
class Cache extends \WebArch\BitrixCache\Cache
{
    protected $_tags = [];


    public function addTag(string $tag)
    {
        parent::addTag($tag);
        if (!$this->hasTag($tag)) {
            $this->_tags[$tag] = $tag;
        }
        return $this;
    }

    public function isTaggedCacheStarted()
    {
        $reflection = new \ReflectionClass($this->getBitrixTaggedCache());
        $compCacheStack = $reflection->getProperty('compCacheStack');
        $compCacheStack->setAccessible(true);
        foreach ($compCacheStack->getValue($this->getBitrixTaggedCache()) as $item) {
            if (current($item) === $this->getPath()) {
                return true;
            }
        }
        return false;
    }

    public function startTaggedCache()
    {
        if (!$this->isTaggedCacheStarted()) {
            $this->getBitrixTaggedCache()->startTagCache($this->getPath());
        }
        return $this;
    }

    public function hasTag($tag): bool
    {
        return array_key_exists($tag, $this->_tags);
    }

    public function registerTag($tag)
    {
        if (!$this->hasTag($tag)) {
            $this->addTag($tag);
            $this->getBitrixTaggedCache()->registerTag($tag);
        }
        return $this;
    }

    public static function createStatic()
    {
        return new static();
    }
}
```

**Comment by webarchitect609** [comment]
> пришлось написать небольшого наследника на скорую руку, может какие идеи появятся.

Есть предложение смотреть на проблему шире. С точки зрения OpenSource. Лицензия моей библиотеки [BSD-3-Clause](https://github.com/webarchitect609/bitrix-cache/blob/master/LICENSE.md) позволяет свободно копировать её и модифицировать под свои нужды. Т.е. можно было сделать fork и дописать всё, что угодно, и пользоваться.

Конечно, при этом возникли бы другие недостатки:
1. Нужно научиться работать с packagist и опубликовать там свою версию.
2. Желательно писать Unit-тесты под новый функционал, а то всё быстро может выйти из-под контроля.
3. Если в будущем в основной библиотеке будет меняться код, и будут появляться новые возможности, то в скопированную/модифицированную версию их нужно будет вручную импортировать, попутно решая все проблемы и конфликты.

И ещё один вариант из той же точки зрения OpenSource: предложить автору свои правки в виде pull-request. Если они приемлемы, если проходят все автоматические проверки, если нет иных недостатков, и если автор жив и выходит на связь, то он может принять эти правки. Так можно стать соавтором.

Ну и, наконец, можно просто открыть Issue, как сделали вы. Тут тоже особенности: автор может долго не отвечать и ничего не исправлять, да и может вовсе отказаться что-то менять.

Описанную вами проблему я в своей практике не встречал, но если с библиотекой можно будет работать и таким образом, то она станет только лучше :) Спасибо :)
