### ISSUE TITLE
AntiStampedeCacheAdapter & cacheenginefiles

### ISSUE THREAD

**Issue by ProklUng** [webarchitect609/bitrix-cache#9]
Добрый день. Вот эта строчка:

$this->maxIdLength = $this->getMaxIdLengthByEngineType(BitrixCache::getCacheEngineType());

при типе cacheenginefiles всегда (как и задумано, исходя из кода) возвращает null. Потом соответственно вываливается с Exception по длине. По моему, это не здорово. Если склонировать в свое пространство имен и убрать !is_numeric($this->maxIdLength), все становится OK.

Еще недостатки. Мой замысел - найти (не писать самому) кэшер для Битрикса, реализующий CacheItemPoolInterface (нужен для использования в связке Guzzle - middleware, Bitrix и сервис-контейнер Symfony). Если поправить вышеуказанное, то AntiStampedeCacheAdapter годится. Но не хватает возможности задавать сеттерами TTL кэша (сейчас он намертво прописывается из конструктора). Path тоже было бы неплохо (чтобы не плодить симфонические сервисы на каждый чих). Или, хотя бы, сделать protected соответствующие свойства. Т.е. речь идет о некоей гибкости конфигурирования конструкции.

Вообще было бы здорово, реализовать версию Cache (а не только AntiStampedeCacheAdapter), реализующую CacheItemPoolInterface. Был бы за такое очень признателен. В целом, отличная работа.

**Comment by webarchitect609** [comment]
Спасибо!

> Вот эта строчка:

> $this->maxIdLength = $this->getMaxIdLengthByEngineType(BitrixCache::getCacheEngineType()); при типе cacheenginefiles всегда (как и задумано, исходя из кода) возвращает null. Потом соответственно вываливается с Exception по длине.

Здесь мне всё понятно — это баг репорт. После его исправления разберу остальную часть, задам дополнительные вопросы. Пока могу сказать лишь следующее:

> Но не хватает возможности задавать сеттерами TTL кэша (сейчас он намертво прописывается из конструктора).

В конструкторе `AntiStampedeCacheAdapter` задаётся время жизни по умолчанию. Посмотрите на метод [`\Psr\Cache\CacheItemInterface::expiresAfter()`](https://github.com/webarchitect609/bitrix-cache/blob/42579d343e21df4ffe91204383c4f40098560ab0/src/main/CacheItem.php#L121). Туда передаётся время жизни конкретного фрагмента кеша. Пример работы с ним содержится в [тесте `\WebArch\BitrixCache\Test\AntiStampedeCacheAdapterTest::testGetThrowsException()` в строке 121](https://github.com/webarchitect609/bitrix-cache/blob/42579d343e21df4ffe91204383c4f40098560ab0/src/test/AntiStampedeCacheAdapterTest.php#L121).

**Comment by ProklUng** [comment]
Спасибо за ответ.

Да, теперь понял (про ТТL Cache & CacheItemPoolInterface). 

Еще малость покрутил этот класс и обнаружил такое (небольшое) неудобство - с $baseDir. Удобно класть кэш по битриксовому стандарту '/cache/SITE_ID/pool'. Сейчас этот путь задается через $baseDir в конструкторе. Т.е. каждый раз надо писать /cache итд. По моему, было бы здорово как-то разнести (опять же, например, дав возможность задавать сеттерами) эти моменты. В своем форке я по-быстрому ввел переменную $basePath, содержащую '/cache'. И в конструкторе задаю ее как-то так: $this->baseDir = $this->basePath . SITE_ID . '/' . $baseDir; Теперь на вход передаю только "pool" (например, psr-cache).

Плюс сеттер (с переинициализацией всей конструкции):

   public function setBaseDir(string $dir): self
    {
        $this->baseDir = $this->basePath . SITE_ID . '/' . $dir;
        $this->init();

        return $this;
    }

init - это следующий вопрос. Так как после использования сеттера нужно всю конструкцию переинициализировать (ведь сервисы, если не указать особо, в контейнере "синглтоны"), то вынес всю сложную механику в отдельный метод. По моему, так лучше - принцип "никакой работы в контейнере", и тому подобное. 

Это все не так важно, но если Вы учтете хоть какие-то пожелания по этому классу, то будет здорово.

**Comment by webarchitect609** [comment]
> Удобно класть кэш по битриксовому стандарту '/cache/SITE_ID/pool'.

Это противоречит основной философии всех разрабатываемых мной пакетов: адаптировать работу с Битрикс под общепринятые в не-Битрикс среде стандарты и практики, оставив максимум гибкости. "Стандарты", которые диктует Битрикс, к сожалению, во многих случаях ущербны и мешают плодотворной работе.

> Сейчас этот путь задается через $baseDir в конструкторе.

Не обязательно менять путь кеша только через `$baseDir`. Можно же задать `$path`, что специально вынесено первым параметром конструктора `AntiStampedeCacheAdapter` и оставлено максимально гибким. Итоговый ключ складывается как:

```php
$baseDir . $path . $key
```

Подробнее см. Битриксовый `\Bitrix\Main\Data\Cache::initCache()`, подразумевая, что их `$initDir` и `$uniqueString` это мои `$path` и `$key` соответственно.

> Так как после использования сеттера нужно всю конструкцию переинициализировать

Это точно лишнее и частично противоречит спецификации [symfony/cache-contracts](https://github.com/symfony/cache-contracts), а также расходится с принципами работы [symfony/cache](https://packagist.org/packages/symfony/cache).

Мне кажется, что вы неверно понимаете назначение pool — это то, что один раз инициализируется и этим дальше пользуются.

> (ведь сервисы, если не указать особо, в контейнере "синглтоны")

Но разве сервисный контейнер Symfony не позволяет создать бесконечное множество объектов пула с самыми разными настройками?

```yaml
foo_cache_pool:
  class: WebArch\BitrixCache\AntiStampedeCacheAdapter
    arguments:
      $path: '/foo'
      $defaultLifetime: 60

bar_cache_pool:
  class: WebArch\BitrixCache\AntiStampedeCacheAdapter
    arguments:
      $path: '/bar/baz'
      $defaultLifetime: 86400
```
